language: node_js
node_js:
  - "10"

os:
  - linux
dist: trusty # to use Ubuntu 14.04

# temporary fix to prevent an issue related to chrome headless. I should restore this to false as soon as possible.
# also I should remove these 2 commands from before_script
# 1. sudo chown root /opt/google/chrome/chrome-sandbox
# 2. sudo chmod 4755 /opt/google/chrome/chrome-sandbox
sudo: true

git:
  depth: 3

env:
  global:
    - secure: GOoX1vNqT8dAl8W+3+21COisLgIDLMAPkc4v/nknxlw4rcJ7kp7o5GHuKW9N4BzvXNMFt403jhL8sUL5slnn0qs4K+6ldW/6YC6BvDPFKC4wpmCFylcbXPIJzJredA6lKF12kKZPE7dtORt0FOfsBlZKtJvqlF75M1cm3SzCzBVuP0/q94K7uFVdGTbvh67Z1uoUC5mlsz9Y6oCMkKMhfZM8abimY8t81nMAHEnjbIKmqkStOtpKrM5ZgHwKUI0j4fhGxSeaErZ2oOer8PztJj9XpAPn7yky/QxdVKqvWzrlishAsU8nEwNVpX0WJFw66m2TVuYGTHbRxcNx4MIQjGNDVlhHh6D3fN27lJtwdUQc6Bkm2R14T0gGKd3w+DbtMfnQPD4x9dTt/agL+C4Glq2WI3ZqM1YBnbfnjukzLBbrF8vqTy3VH6lI4JVxEQnHQ84mCe7lvDVWv/wO7zY63s6hZxXvl/r+Z7hZ1m+VRUjnips0Abri3AW2EP/fUkeiR163f7/xKj0oI65mCLPCm5ntAL1YxHItJtnfq+1PulGiFggrZt8HEAGDDS8gQit57AxV8TxJnsg++E0SdhVRRUCD5/lURLj/Uy+gVs+GHyVM5sGv2LDy57ddXv7vYQOxI7MoC/MiG3XX6irULCs+wykDTzLkENBCgmxALRsLKxI= # CODECLIMATE
    - secure: VQffWPp3fa0UrshHHtspgvRj9WIaoOgkg0+5O5AFFPbwvEh/ACHeLZbxFzlMyuoahH9MZ4bYMVEnZvQjg9v86Z24+cH1bYZrCBbPqkKiM0Z3eUhTeZZlDBYbBmY1WtDZarMGHjznkz0kFXgHbggE1cqmDs/WDnvdZBhLTKOKKlZRM4iTPsmP/DWd0neQPDb7qStYx1Fp+lXvb+os3h09czDNY2jx+9LF3k3jxOWfPOEYdlKwp5dOUG8MTzMN2hhdy7XU9uLqMtiB/sS0DqafvgmlHvgnJmkx4Hdn1Ae3O0amVxJbx6e+J821AfrSCQqkLG9IX6mvplXZ8BRHn+9cgRXKJbyhFb2mIkJHwylatoPHagW9Nql62LcYTTsdnrgcYFpfciAEnIfNHwXm8IM3e80UPsvaZR2SpCmP7CdZJ8GFDdAzBtjgPyS311AKGMfergQbET8EZ34AVxfNjj0UTP7uJ9Mm35kd2zEK8bV1ZPbxP/EIKOn6IL6nqXoHhJphgKHbV/OdTUaHd7p5RUjSHGZdMM8DYqkSW7cMprc98//lUnA1O1HjnLbBBHOzK4XEKeEprM/9GCvOYLOTwABa6IgiltYf6JEEy/MHnBtYaBVk/bnj/LOV2OCANk9qBlmTLL+VRRmpnmQYV7WQIXhwP8GRZt04fXHgyJfCbWxXbKI= # COVERALLS
    - secure: lGnfg86i8xQWtRqDNqzYh0jqhh0XBsRev6rwKvtccP9Ql5b4ZGDnvdxVASZLBF4fpSFZOeS36ciIGv1gxNQvISFBl3JIesDZjxWiSwMa3/mc5sVfDKuQaSeQ7QMgY0HakrBjKj8iOzu47jMTUBOpFsNtTffTZP31tlDrtkb0IoxmQYFRdWuWGpy3FBAzc+bAQI4W1XCELX/zMvqAJDgt3LrO6EzeU/D8M85DIZPmj2jA8hs5ODRuQnwPCfqoNqJWdMU3IbyHLYgApji6CJidkyiT78mOFcsedtyqUK8dF9FhoZI4FEMLqd/xqvFDzrwyBN6d8/7+gBMYqrYyskXhLjvQnz4op2TMgl0CyuVTNGmSi92kXJXbwQq/D7SPtBEL1Ca3q2V0Qwt0j+qQXz4uXKiUtKC5ufZAzvvmEFq0w801i4bXfLPqZFQwL1Va1diaH/n/dfw60jYuBQ5T/XySEkpfLzIdr0hZaQkS/s6xZiyKKVhvvlrGK8QrW9RyEI6GMnES3zcKFLkw6frVR8ynjqCI0ucNWr+PpkaWbrjRsn41VLUAGrijj1TF0z7IXbXmd4MY9N3zhUKSZIgPJoBd29asM7Yxoqkrua1ZxFaSrmUsyhke+OxJBBMEoLWb31ldvn1HL3RYJ7KwVFmeMVDu8aKK/4aUtd/WP79t5jU88/o= # SONARCLOUD

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "ks89-github"
    token:
      secure: "lGnfg86i8xQWtRqDNqzYh0jqhh0XBsRev6rwKvtccP9Ql5b4ZGDnvdxVASZLBF4fpSFZOeS36ciIGv1gxNQvISFBl3JIesDZjxWiSwMa3/mc5sVfDKuQaSeQ7QMgY0HakrBjKj8iOzu47jMTUBOpFsNtTffTZP31tlDrtkb0IoxmQYFRdWuWGpy3FBAzc+bAQI4W1XCELX/zMvqAJDgt3LrO6EzeU/D8M85DIZPmj2jA8hs5ODRuQnwPCfqoNqJWdMU3IbyHLYgApji6CJidkyiT78mOFcsedtyqUK8dF9FhoZI4FEMLqd/xqvFDzrwyBN6d8/7+gBMYqrYyskXhLjvQnz4op2TMgl0CyuVTNGmSi92kXJXbwQq/D7SPtBEL1Ca3q2V0Qwt0j+qQXz4uXKiUtKC5ufZAzvvmEFq0w801i4bXfLPqZFQwL1Va1diaH/n/dfw60jYuBQ5T/XySEkpfLzIdr0hZaQkS/s6xZiyKKVhvvlrGK8QrW9RyEI6GMnES3zcKFLkw6frVR8ynjqCI0ucNWr+PpkaWbrjRsn41VLUAGrijj1TF0z7IXbXmd4MY9N3zhUKSZIgPJoBd29asM7Yxoqkrua1ZxFaSrmUsyhke+OxJBBMEoLWb31ldvn1HL3RYJ7KwVFmeMVDu8aKK/4aUtd/WP79t5jU88/o="
jdk:
  - oraclejdk8

matrix:
  fast_finish: true

before_install:
  - source travisci/before_install.sh
install:
  - bash travisci/install.sh
after_install:
  - npm rebuild node-sass
before_script:
  - source travisci/before_script.sh # starts in the same shell
script:
  - bash travisci/script.sh
after_success:
  - source travisci/after_success.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  apt: true
  bundler: true
  directories:
    - ./node_modules
    - ./examples/angular-cli/node_modules
    - ./examples/angular-cli-6/node_modules
    - ./examples/angular-cli-material/node_modules
    - ./examples/systemjs/node_modules
    - ./examples/universal/node_modules
    - '$HOME/.sonar/cache'
